### PR TITLE
Implemented import dashboards from a directory

### PR DESCRIPTION
**Pull request by vrymar**
Solution for issue #25.

### CODE REVIEW

**Comment by amotl** [comment]
Also thanks for this excellent improvement, Vitalii. Can you also reformat the code to satisfy CI, like you did with your other patch?

**Comment by vitaliirymar** [comment]
Will do tomorrow

**Comment by vrymar** [comment]
Hi @amotl ! Not sure why export tests are failing, as this functionality was not touched. Checking...

**Comment by amotl** [comment]
Maybe you need to rebase your branch on top of main?

**Comment by vrymar** [comment]
Closing this PR and creating a new one rebased on upstream/main

**Pull request closed without merging**
